-- Create a new table
CREATE TABLE league(
  gameId BIGINT,
  blueWins INT,
  blueWardsPlaced INT,
  blueWardsDestroyed INT,
  blueFirstBlood INT,
  blueKills INT,
  blueDeaths INT,
  blueAssists INT,
  blueEliteMonsters INT,
  blueDragons INT,
  blueHeralds INT,
  blueTowersDestroyed INT,
  blueTotalGold INT,
  blueAvgLevel float,
  blueTotalExperience INT, 
  blueTotalMinionsKilled INT,
  blueTotalJungleMinionsKilled INT,
  blueGoldDiff INT,
  blueExperienceDiff INT,
  blueCSPerMin float,
  blueGoldPerMin float,
  redWardsPlaced INT, 
  redWardsDestroyed	INT, 
  redFirstBlood INT,
  redKills INT,
  redDeaths INT,
  redAssists INT,
  redEliteMonsters INT,
  redDragons INT,
  redHeralds INT,
  redTowersDestroyed INT,
  redTotalGold INT,
  redAvgLevel float,
  redTotalExperience INT,
  redTotalMinionsKilled INT,
  redTotalJungleMinionsKilled INT,
  redGoldDiff INT,
  redExperienceDiff INT,
  redCSPerMin float,	
  redGoldPerMin float
);

select * from league